# Generated by Django 4.1.6 on 2023-02-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.BooleanField(default=True, verbose_name='En stock')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('size', models.CharField(max_length=10, verbose_name='tamaño')),
            ],
        ),
    ]
