# Generated by Django 4.1.6 on 2023-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Imagen'),
        ),
    ]
